export const artists = [
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
   {
       artistImg: '../img/artista-1.jpg',
       name: 'Nome Cognome',
       fbUrl: 'https://www.facebook.com/doctorinktattoostudio.monza',
       IgUrl: 'https://www.instagram.com/doctorinktattoostudio/?hl=it',
       twitterUrl: '',
   },
];